model:
  n_atoms: 10
  embedding_dim: 48
  n_attention: 8
  local_dim: 128
  num_head: 8
  global_dim: 128
  dense_out: 128
  scale: 0.5
  use_attn_norm: True
  use_ga_norm: True
  use_ring: False
  gaussian_d: 4.0
  g_update: True
hyper:
  batch_size: 128
  test_percent: 0.1
  scheduler: "cosine"
  train_size: 110000
  test_size: 10829
  data_size: 130829
  data_nei_path: "../data/processed_data/qm9_std_jctc/qm9_std_jctc_data_neighbor_dt4.0_wt0.2.npy"
  data_energy_path: "../data/processed_data/qm9_std_jctc/qm9_std_jctc_data_energy.npy"
  lr: 0.0006
  min_lr: 0.00008
  save_path: "trained_models/paper_reports/model_qm9_scannet+"
  pretrained: ""
