model:
  n_attention: 2
  n_atoms: 3
  n_embedding: 4
  dense_embed: 32
  dim_ofm: 32
  v_dim: 32
  num_head: 1
  dim: 32
  dense_out: 32
  
hyper:
  batch_size: 64
  test_size: 0.2
  data_path: 'preprocess/h2o_voroinn_neigh.npy'
  lr: 0.001
  decay: 0.85
  save_path: 'model_h2o'


