model:
  n_atoms: 10
  embedding_dim: 48
  n_attention: 8
  local_dim: 128
  num_head: 8
  global_dim: 128
  dense_out: 128
  scale: 0.5
  use_attn_norm: True
  use_ga_norm: True
  use_ring: True
hyper:
  batch_size: 128
  test_percent: 0.1
  train_size: ''
  test_size: ''
  data_size: 3000
  data_nei_path: 'processed_data/fullerene/fullerene_data_neighbor_dt4.0_wt0.2.npy'
  data_energy_path: 'processed_data/fullerene/fullerene_data_energy.npy'
  lr: 0.0005
  min_lr: 0.00005
  save_path: 'trained_models/model_fullerene'
  pretrained: ''
