model:
  n_attention: 3
  n_atoms: 9
  n_embedding: 64
  dense_embed: 64
  dim_ofm: 64
  v_dim: 64
  num_head: 1
  dim: 64
  dense_out: 32
  
hyper:
  batch_size: 64
  test_size: 0.1
  data_size: 9999
  data_nei_path: 'preprocess/h2o_voroinn_neigh_3.npy'
  data_energy_path: 'preprocess/h2o_energy.npy'
  data_ofm_path: 'preprocess/ofm_local_reps_latxb.pickle'
  struct_ofm_path: 'preprocess/ofm_struct_reps_latxb.pickle'
  lr: 0.0005
  decay: 0.85
  save_path: 'trained_models/model_h2o_new_8'
