model:
  n_attention: 4
  n_atoms: 10
  n_embedding: 128
  dense_embed: 128
  dim_ofm: 128
  v_dim: 128
  num_head: 1
  dim: 128
  dense_out: 64
  
hyper:
  batch_size: 64
  test_size: 0.1
  data_size: 7607
  data_nei_path: 'preprocess/latxb_voroinn_neigh_2.npy'
  data_energy_path: 'preprocess/latxb_energy.npy'
  data_ofm_path: 'preprocess/ofm_local_reps_latxb.pickle'
  struct_ofm_path: 'preprocess/ofm_struct_reps_latxb.pickle'
  lr: 0.001
  decay: 0.85
  save_path: 'model_latxb_8'